{
 "title": "OpenRec Overview",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Running",
   "type": "stat",
   "description": "Total number of controls currently running",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "controls_running" }
   ]
  },
  {
   "title": "Suspended",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 2, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "controls_suspended" }
   ]
  },
  {
   "title": "Disabled",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 4, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "controls_disabled" }
   ]
  },
  {
   "title": "Match Jobs",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "controls_matching" }
   ]
  },
  {
   "title": "Inbox Size",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "control_inbox_size_bytes", "legendFormat": "{{control_name}}" }
   ]
  },
  {
   "title": "Outbox Size",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "control_outbox_size_bytes", "legendFormat": "{{control_name}}" }
   ]
  },
  {
   "title": "Unmatched Txs",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 4 },
   "targets": [
    { "expr": "unmatched_total" }
   ]
  },
  {
   "title": "Umatched Txs By Control",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 16, "x": 8, "y": 7 },
   "targets": [
    { "expr": "control_unmatched_txs", "legendFormat": "{{control_name}}" }
   ]
  },
  {
   "title": "OpenRec Disk Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "disk_usage_total{instance=\"OpenRec_Steward\",job=\"overview\"}"
    }
   ]
  }
 ]
}