version: '3.7'

volumes:
  prometheus_data: {}
  grafana-storage: {}

networks:
  openrec_net:

services:
  openrec:
    image: grandmastertash/openrec:v0.1.0-alpha
    container_name: openrec
    user: "${OPENREC_UID}:${OPENREC_GID}"
    volumes:
     - ./etc:/etc/openrec/
     - ../examples/01-Basic-Match.yaml:/etc/openrec/charters/01-Basic-Match.yaml
     - ../examples/02-Projected-Columns.yaml:/etc/openrec/charters/02-Projected-Columns.yaml
     - ../examples/03-Net-With-Tolerance.yaml:/etc/openrec/charters/03-Net-With-Tolerance.yaml
     - ../examples/04-3-Way-Match.yaml:/etc/openrec/charters/04-3-Way-Match.yaml
     - ../examples/05-2-Stage-Match.yaml:/etc/openrec/charters/05-2-Stage-Match.yaml
     - ../examples/07-Unmatched-Data.yaml:/etc/openrec/charters/07-Unmatched-Data.yaml
     - ../examples/08-Advanced-Lua-Scripts.yaml:/etc/openrec/charters/08-Advanced-Lua-Scripts.yaml
     - ../examples/09-Changesets.yaml:/etc/openrec/charters/09-Changesets.yaml
     - ../examples/10-Performance.yaml:/etc/openrec/charters/10-Performance.yaml
     - ../examples/11-Group-By-Dates.yaml:/etc/openrec/charters/11-Group-By-Dates.yaml
     - ../examples/12-FXRate-Lookups.yaml:/etc/openrec/charters/12-FXRate-Lookups.yaml
     - ../examples/13-The-Kitchen-Sink.yaml:/etc/openrec/charters/13-The-Kitchen-Sink.yaml
     - ./data:/data
    environment:
     - RUST_LOG=info
    links:
     - pushgateway:pushgateway
    depends_on:
     - pushgateway
     - prometheus
     - grafana
    networks:
      - openrec_net

  prometheus:
    image: prom/prometheus:v2.32.0
    container_name: prometheus
    volumes:
      - ./prometheus/:/etc/prometheus/
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    ports:
      - 9090:9090
    links:
     - pushgateway:pushgateway
    depends_on:
     - pushgateway
    networks:
      - openrec_net
    restart: unless-stopped

  pushgateway:
    image: prom/pushgateway:v1.4.2
    container_name: pushgateway
    restart: unless-stopped
    expose:
      - 9091
    ports:
      - "9091:9091"
    networks:
      - openrec_net

  grafana:
    image: grafana/grafana-oss:8.3.3
    container_name: grafana
    restart: unless-stopped
    environment:
     - GF_SECURITY_ADMIN_USER=admin
     - GF_SECURITY_ADMIN_PASSWORD=admin
     - GF_USERS_ALLOW_SIGN_UP=false
    volumes:
     - grafana-storage:/var/lib/grafana
     - ./grafana/provisioning/:/etc/grafana/provisioning/
    ports:
     - "3000:3000"
    networks:
      - openrec_net