version: '3.7'

volumes:
  prometheus_data: {}
  grafana-storage: {}

networks:
  openrec_net:

services:
  openrec:
    # TODO: Build with context, etc...
    image: openrec:latest
    container_name: openrec
    user: "${UID}:${GID}"
    volumes:
     - ./etc:/etc/openrec/
     - ./data:/data
    # environment:
    #  - RUST_LOG=trace
    links:
     - pushgateway:pushgateway
    depends_on:
     - pushgateway
     - prometheus
     - grafana
    networks:
      - openrec_net

  prometheus:
    image: prom/prometheus:v2.32.0
    container_name: prometheus
    volumes:
      - ./prometheus/:/etc/prometheus/
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    ports:
      - 9090:9090
    links:
     - pushgateway:pushgateway
    depends_on:
     - pushgateway
    networks:
      - openrec_net
    restart: unless-stopped

  pushgateway:
    image: prom/pushgateway:v1.4.2
    container_name: pushgateway
    restart: unless-stopped
    expose:
      - 9091
    ports:
      - "9091:9091"
    networks:
      - openrec_net

  grafana:
    image: grafana/grafana-oss:8.3.3
    container_name: grafana
    restart: unless-stopped
    environment:
     - GF_SECURITY_ADMIN_USER=admin
     - GF_SECURITY_ADMIN_PASSWORD=admin
     - GF_USERS_ALLOW_SIGN_UP=false
    volumes:
     - grafana-storage:/var/lib/grafana
     - ./grafana/provisioning/:/etc/grafana/provisioning/
    ports:
     - "3000:3000"
    networks:
      - openrec_net