[package]
name = "core"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde_yaml = "0.8"
rust_decimal = "1.17"
thiserror = "1.0"
humantime = "2.1.0"
ansi_term = "0.12"